apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-cicd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k3s-cicd-app
  template:
    metadata:
      labels:
        app: k3s-cicd-app
    spec:
      containers:
        - name: k3s-cicd-app
          image: DOCKER_IMAGE_TAG
          ports:
            - containerPort: 8080