apiVersion: v1
kind: Service
metadata:
  name: k3s-cicd-service
spec:
  selector:
    app: k3s-cicd-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080